version: "3.9"

services:
  database_posts:
    image: postgres
    restart: always
    container_name: "database_posts"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5480:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge