# Generated by Django 4.2.10 on 2024-02-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-is_published'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['-is_published'], name='post_is_publ_c738d1_idx'),
        ),
    ]
